version: 3,
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - 27017:27017
    volumes:
      - ./mongo-data:/data/db
    restart: always
    command: --wiredTigerCacheSizeGB 1.5
  top-api:
    image: top-api:latest
    container_name: top-api
    ports:
      - 3000:3000
    depends_on:
      - mongo
    env_file:
      - .env
    restart: always
